### ISSUE TITLE
自定义邮件“新Memo提及模板”不生效

### ISSUE THREAD

**Issue by zwfpro** [RandallAnjie/moments#10]
版本：v0.4.5
问题：设置新Memo提及模板之后不生效，依旧是以默认模版进行邮件通知
图片：
![IMG_20240702_132617_Mosaic_13_26_22.jpg](https://vip.helloimg.com/i/2024/07/02/66838f022e622.jpg)

**Comment by RandallAnjie** [comment]
已经复现，应该是当时写的时候漏掉了，下个版本修复，感谢提醒

**Comment by zwfpro** [comment]
评论提及是不是还没写，我看有邮件通知但是评论时没有找到艾特按钮，不知道是不是bug

**Comment by RandallAnjie** [comment]
评论提及确实还没实现，应该当时原版的评论是不保存用户id的，只存了用户名，当时懒了没改这块，现在要动这块的逻辑就有点复杂了，之后我想想办法加上吧
