### ISSUE TITLE
关于百度的广告跟踪

### ISSUE THREAD

**Issue by zliuboy** [RandallAnjie/moments#12]
请问安装完成以后，有百度的广告跟踪。这个程序是什么内容产生的百度广告跟踪的呀，是否可以移除。如果不能移除，我是否能本地屏蔽该链接，会造成不好的后果吗？

赞美randall@RandallAnjie

**Comment by RandallAnjie** [comment]
您好，感谢提出疑问，这个百度的跟踪链接是由天气的iflame发起的，当时我图省事直接引入了这个iflame，您可以在后台，设置 `启用首页天气展示` 选项为关闭状态即可关闭该问题

<img width="656" alt="截屏2024-07-13 02 49 06" src="https://github.com/user-attachments/assets/3b7dc3c4-7f28-4bfd-be91-86d78eac1ae5">
