### ISSUE TITLE
memo回复评论邮件通知对象错误

### ISSUE THREAD

**Issue by zwfpro** [RandallAnjie/moments#13]
别人评论了memo之后，回复这个评论，邮件通知对象应是该评论人，现在是回复评论之后邮件通知的对象是memo的作者，这导致每次回复别人评论之后邮件会通知自己回复了自己，这个应该也是个bug了。

**Comment by RandallAnjie** [comment]
目前邮件通知的逻辑是根据事件优先级高低依次通知，同时如果两个事件需要发送的是同一个邮箱的话则会优先发送优先级较高的事件，忽略优先级较低的事件

事件优先级排序：

1. 回复用户时，被回复的用户的邮件通知
2. 产生评论时（无论是不是回复），该Memo提及到的所有用户的邮件通知
3. 产生评论时（无论是不是回复），该Memo的作者收到邮件通知

举个例子：
- 比如A发了一条Memo，这条Memo提及了B，这时候A评论了这条Memo的时候，A不会收到邮件通知，B会收到通知。
- 如果C回复了A的评论，A先收到回复通知，B收到提及评论通知
- 如果D回复了C，则C先收到回复通知，其次A和B都收到（提及）评论通知

最后，如果发表（或者修改）的时候提及了某个用户，该用户也会收到邮件通知（这个应该不在本issue的讨论范围了）

**Comment by luvzwf** [comment]
现在出现的问题是A发表了一个memo，B评论了这条memo，A回复B的评论，B不会收到邮件通知，A会收到邮件通知。

**Comment by zwfpro** [comment]
找到原因了，好像是gmail的问题，感谢作者的辛苦付出🙏
