### ISSUE TITLE
上传照片时能否一次性多选，一键批量上传

### ISSUE THREAD

**Issue by jolly90s** [RandallAnjie/moments#17]
开发大佬，你好，我用苹果手机在上传照片时只能选一个，传一个，然后再选一个，再继续传，能否一次性多选，一键批量上传？这个实现起来是不是很复杂？

**Comment by RandallAnjie** [comment]
这个还是比较好实现的，因为性能问题现在没有在继续开发这个了，可以等等明年重新写一个，或者去看看原版用go写的版本

**Comment by jolly90s** [comment]
> 这个还是比较好实现的，因为性能问题现在没有在继续开发这个了，可以等等明年重新写一个，或者去看看原版用go写的版本

OK
