### ISSUE TITLE
这个项目怎么部署使用呢

### ISSUE THREAD

**Issue by dinphy** [RandallAnjie/moments#2]
正在使用原项目，docker镜像的。
这个不是docker镜像，该怎么使用呢

**Comment by RandallAnjie** [comment]
目前正在添加最后一些小功能，优化使用体验，和批量修复bug的阶段，等bug修复差不多了就会打成docker镜像供大家使用

**Comment by RandallAnjie** [comment]
部署教程[https://blog.randallanjie.com/archives/1714872362028](https://blog.randallanjie.com/archives/1714872362028)
