### ISSUE TITLE
成功通过宿主机方式启动项目

### ISSUE THREAD

**Issue by dinphy** [RandallAnjie/moments#5]
具体操作如下：

### 先拉镜像

```html
docker pull ranjie/rmoments:v0.3.8
```

### 创建并启动容器

```html
docker run -d --name rmoments ranjie/rmoments:v0.3.8
```

### 更改端口号（如果需要）

1. 先复制 docker-compose.yaml 到宿主机

```html
docker cp rmoments:/app/docker-compose.yaml /data/docker
```

2. 将其中的 3000 改为您希望使用的端口号，例如 5000：

```html
ports:
  - '127.0.0.1:5000:3000'
```

3. 修改完以后，将 docker-compose.yaml 复制到容器

```html
docker cp /data/docker/docker-compose.yaml rmoments:/app/
```

### 运行项目

```html
cd /data/docker
docker-compose up -d
```

遇到的问题：试了一下不能上传图片。

**Comment by RandallAnjie** [comment]
1. 如果你需要更改端口号的话不需要重新将docker-compose.yaml文件重新放回容器，直接根据[本仓库wiki中的docker启动章节](https://github.com/RandallAnjie/moments/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95#docker%E5%90%AF%E5%8A%A8)进行查看
2. 图片上传失败的问题大概率是由于你的容器里的环境变量出现问题了，请排查一下你的data/upload目录下是否有上传的文件，可能是上传成功，但是环境变量出错导致无法获取到这个图片

**Comment by dinphy** [comment]
> 1. 如果你需要更改端口号的话不需要重新将docker-compose.yaml文件重新放回容器，直接根据[本仓库wiki中的docker启动章节](https://github.com/RandallAnjie/moments/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95#docker%E5%90%AF%E5%8A%A8)进行查看
> 2. 图片上传失败的问题大概率是由于你的容器里的环境变量出现问题了，请排查一下你的data/upload目录下是否有上传的文件，可能是上传成功，但是环境变量出错导致无法获取到这个图片

对头，就是这个上传目录的问题。
你能简化下我的操作吗？顺便也告知我这个环境如何配置

**Comment by RandallAnjie** [comment]
现在你直接使用命令：
```shell
curl -o docker-compose.yaml https://cdn.jsdelivr.net/gh/RandallAnjie/moments/docker-compose.yaml
```
获取到 `docker-compose.yaml`

然后直接运行 `docker-compose up` -d 或者 `docker compose up -d` 就可以了

如果已经安装了redis，就需要修改docker包里的环境变量了，这样就不如自行从源码部署，或者自行打包了，等之后我再想想有什么别的办法能解决这个问题吧

**Comment by dinphy** [comment]
> 现在你直接使用命令：
> 
> ```shell
> curl -o docker-compose.yaml https://cdn.jsdelivr.net/gh/RandallAnjie/moments/docker-compose.yaml
> ```
> 
> 获取到 `docker-compose.yaml`
> 
> 然后直接运行 `docker-compose up` -d 或者 `docker compose up -d` 就可以了
> 
> 如果已经安装了redis，就需要修改docker包里的环境变量了，这样就不如自行从源码部署，或者自行打包了，等之后我再想想有什么别的办法能解决这个问题吧

这链接 拉不下来，才另辟他路的。

**Comment by RandallAnjie** [comment]
你直接将仓库根目录的docker-compose.yaml复制下去就行了，这个curl一串代码的意思就是通过jsdelivr的cdn下载仓库根目录的docker-compose.yaml文件
