### ISSUE TITLE
出现500报错

### ISSUE THREAD

**Issue by Darvyn** [RandallAnjie/moments#7]
更新到最新的v0.4.2_with_redis版本后出现了报错：

app-1  | OK
app-1  | Listening on http://[::]:3000
app-1  | [nuxt] [request error] [unhandled] [500] 
app-1  | Invalid `prisma.notification.findFirst()` invocation:
app-1  | 
app-1  | 
app-1  | The table `main.Notification` does not exist in the current database.
app-1  |   at In.handleRequestError (./.output/server/node_modules/@prisma/client/runtime/library.js:122:6877)  
app-1  |   at In.handleAndLogRequestError (./.output/server/node_modules/@prisma/client/runtime/library.js:122:6211)  
app-1  |   at In.request (./.output/server/node_modules/@prisma/client/runtime/library.js:122:5919)  
app-1  |   at async l (./.output/server/node_modules/@prisma/client/runtime/library.js:127:11167)  
app-1  |   at async Object.handler (./.output/server/chunks/routes/api/site/config/get.get.mjs:23:22)  
app-1  |   at async Object.handler (./.output/server/chunks/runtime.mjs:3267:19)  
app-1  |   at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3533:7)
app-1  | [nuxt] [request error] [unhandled] [500] 
app-1  | Invalid `prisma.memo.findMany()` invocation:

**Comment by make858** [comment]
这个启动有点慢

**Comment by make858** [comment]
这个启动有点慢

**Comment by RandallAnjie** [comment]
已经重新发布0.4.2版本，全部更新了数据库结构，请重新尝试一下

**Comment by RandallAnjie** [comment]
> 这个启动有点慢

如果用带有redis的脚本启动的话，就需要等待redis启动完成后才能启动moments，你也可以尝试进行优化，感谢反馈

**Comment by Darvyn** [comment]
> 已经重新发布0.4.2版本，全部更新了数据库结构，请重新尝试一下

重新更新，现在看起来正常了，感谢
