### ISSUE TITLE
发图片不会显示

### ISSUE THREAD

**Issue by make858** [RandallAnjie/moments#8]
![XE~A(ABP U( R9933GOOJ_Y](https://github.com/RandallAnjie/moments/assets/64182739/0bde2147-f6ea-49ae-87c3-024561260992)
![截图20240601143635](https://github.com/RandallAnjie/moments/assets/64182739/a82a6e19-9e1c-4862-8b89-dd5753361c05)
请看

**Comment by RandallAnjie** [comment]
请检查一下容器挂载目录下的 `upload` 文件夹是否存在，如果不存在请自行创建，脚本应该是会检查并且自行创建该目录的

**Comment by RandallAnjie** [comment]
看到你用的是0.4.1版本的，新版本0.4.2已经修复这个问题了哈

[v0.4.2更新Commit](https://github.com/RandallAnjie/moments/commit/7f0e6eeab3198fa1d4f8a1e5703655e35e029ca9)

[v0.4.2更新日志](https://m.zhuanjie.ltd/detail/106)
