### ISSUE TITLE
匿名用户可以访问配置页面,key丢失风险

### ISSUE THREAD

**Issue by mdzz9527** [RandallAnjie/moments#9]
![image](https://github.com/RandallAnjie/moments/assets/39895740/8d47aae3-784a-4959-b4ed-2e2a3d90483d)

**Comment by mdzz9527** [comment]
https://momentscf.randallanjie.com/config

**Comment by RandallAnjie** [comment]
你说的这个页面无权限看到的key都是可以公开的key，别人拿到也只能在这个站点使用，为了显示舒服点，下个版本在我前端也拦住这个页面

**Comment by RandallAnjie** [comment]
已经修复，请等待新版本发布 [4f087ba](https://github.com/RandallAnjie/moments/commit/4f087bad4864fef6fd9b78855d0a842581fd3a5e)
